-- Supabase Schema Setup for ResearchHub AI

-- =======================================================================================
-- Workspaces Table
-- Represents a collection/project containing many research papers
-- =======================================================================================
CREATE TABLE workspaces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Row Level Security (RLS) for Workspaces
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only view their own workspaces" 
ON workspaces FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own workspaces" 
ON workspaces FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own workspaces" 
ON workspaces FOR DELETE 
USING (auth.uid() = user_id);


-- =======================================================================================
-- Papers Table
-- Represents a single parsed document stored within a workspace
-- Metadata extracted by Unstructured.io will be saved here in JSONB format
-- =======================================================================================
CREATE TABLE papers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title VARCHAR(500) NOT NULL,
    authors TEXT[],
    abstract TEXT,
    published_date DATE,
    source_url TEXT,
    original_filename VARCHAR(255),
    metadata JSONB DEFAULT '{}'::jsonb, -- unstructured.io full metadata
    qdrant_collection_id VARCHAR(255), -- References the vector db collection identifying this paper's chunks
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Row Level Security (RLS) for Papers
ALTER TABLE papers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only view their own papers" 
ON papers FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own papers" 
ON papers FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own papers" 
ON papers FOR DELETE 
USING (auth.uid() = user_id);

-- =======================================================================================
-- Research Insights Table
-- Stores autonomous findings (summaries, contradictions, gaps) generated by AI Agents
-- =======================================================================================
CREATE TABLE research_insights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL, -- 'summary', 'contradiction', 'research_gap'
    content TEXT NOT NULL,
    source_papers JSONB, -- Array of paper IDs that contributed to this insight
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Row Level Security (RLS) for Research Insights
ALTER TABLE research_insights ENABLE ROW LEVEL SECURITY;

-- We need to join workspaces to check if the user owns the workspace for the insight
CREATE POLICY "Users can only view insights in their own workspaces" 
ON research_insights FOR SELECT 
USING (
    EXISTS (
        SELECT 1 FROM workspaces WHERE workspaces.id = research_insights.workspace_id AND workspaces.user_id = auth.uid()
    )
);

CREATE POLICY "Users can insert insights in their own workspaces" 
ON research_insights FOR INSERT 
WITH CHECK (
    EXISTS (
        SELECT 1 FROM workspaces WHERE workspaces.id = research_insights.workspace_id AND workspaces.user_id = auth.uid()
    )
);

CREATE POLICY "Users can delete insights in their own workspaces" 
ON research_insights FOR DELETE 
USING (
    EXISTS (
        SELECT 1 FROM workspaces WHERE workspaces.id = research_insights.workspace_id AND workspaces.user_id = auth.uid()
    )
);
