import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { fetchApi, API_BASE_URL } from "../lib/api";
import { supabase } from "../lib/supabase";
import { FileText, AlertTriangle, Target, Loader2, Clock, Download, FileDown, File } from "lucide-react";

interface Insight {
    id: string;
    type: "summary" | "contradiction" | "research_gap";
    content: string;
    created_at: string;
}

interface InsightsPanelProps {
    workspaceId: string | null;
}

export default function InsightsPanel({ workspaceId }: InsightsPanelProps) {
    const [insights, setInsights] = useState<Insight[]>([]);
    const [isLoading, setIsLoading] = useState(false);
    const [isExporting, setIsExporting] = useState<"none" | "pptx" | "md" | "pdf">("none");
    const [filter, setFilter] = useState<"all" | "summary" | "contradiction" | "research_gap">("all");

    // Fetch insights when workspace changes
    useEffect(() => {
        if (!workspaceId) {
            setInsights([]);
            return;
        }

        const loadInsights = async () => {
            setIsLoading(true);
            try {
                const res = await fetchApi(`/chat/insights/${workspaceId}`);
                setInsights(res.data || []);
            } catch (err) {
                console.error("Failed to fetch insights:", err);
            } finally {
                setIsLoading(false);
            }
        };

        loadInsights();

        // Polling every 5 seconds to catch new insights generated by background agents
        const interval = setInterval(loadInsights, 5000);
        return () => clearInterval(interval);

    }, [workspaceId]);

    const handleExport = async (type: "pptx" | "md" | "pdf") => {
        if (!workspaceId) return;
        setIsExporting(type);
        try {
            const { data: { session } } = await supabase.auth.getSession();
            const token = session?.access_token;

            let endpoint = `${API_BASE_URL}/workspaces/${workspaceId}/export/${type === "md" ? "markdown" : type}`;

            const response = await fetch(endpoint, {
                method: "GET",
                headers: token ? { "Authorization": `Bearer ${token}` } : {}
            });

            if (!response.ok) {
                const errorData = await response.json().catch(() => ({ detail: "Export failed" }));
                throw new Error(errorData.detail || "Export failed. You may need to install wkhtmltopdf for PDF export.");
            }

            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;

            // Try to extract filename from Content-Disposition if available
            const contentDisposition = response.headers.get('Content-Disposition');
            let filename = `Research_Insights.${type}`;
            if (contentDisposition && contentDisposition.includes('filename=')) {
                filename = contentDisposition.split('filename=')[1].replace(/"/g, '');
            }

            a.download = filename;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);
        } catch (err: any) {
            console.error(`Failed to export ${type.toUpperCase()}:`, err);
            alert(`Failed to export presentation: ${err.message}`);
        } finally {
            setIsExporting("none");
        }
    };

    const filteredInsights = insights.filter(i => filter === "all" || i.type === filter);

    const getTypeDetails = (type: string) => {
        switch (type) {
            case "summary":
                return { icon: <FileText size={16} />, color: "text-blue-400", bg: "bg-blue-500/10", border: "border-blue-500/20", label: "Summary" };
            case "contradiction":
                return { icon: <AlertTriangle size={16} />, color: "text-rose-400", bg: "bg-rose-500/10", border: "border-rose-500/20", label: "Contradiction" };
            case "research_gap":
                return { icon: <Target size={16} />, color: "text-emerald-400", bg: "bg-emerald-500/10", border: "border-emerald-500/20", label: "Research Gap" };
            default:
                return { icon: <FileText size={16} />, color: "text-white/70", bg: "bg-white/5", border: "border-white/10", label: "Insight" };
        }
    };

    if (!workspaceId) {
        return (
            <div className="h-full flex flex-col items-center justify-center text-white/40 border-l border-white/5 bg-[#0a0a0f]/50 p-6 text-center">
                <FileText size={32} className="mb-4 text-white/20" />
                <p>Select a workspace to view autonomous insights.</p>
            </div>
        );
    }

    return (
        <div className="h-full flex flex-col border-l border-white/5 bg-[#0a0a0f]/50 overflow-hidden">
            <div className="p-6 border-b border-white/5">
                <div className="flex flex-col mb-1 gap-2">
                    <h2 className="text-white font-semibold text-lg flex items-center gap-2">
                        <SparklesIcon /> Autonomous Insights
                    </h2>
                    {insights.length > 0 && (
                        <div className="flex bg-[#12121a] rounded-lg border border-white/10 p-1 w-full mt-2">
                            <button
                                onClick={() => handleExport("md")}
                                disabled={isExporting !== "none"}
                                className={`flex-1 flex flex-shrink-0 items-center justify-center gap-1.5 px-2 py-1.5 disabled:opacity-50 text-white rounded-md text-[10px] font-medium transition-colors ${isExporting === "md" ? "bg-violet-600" : "hover:bg-white/10"}`}
                            >
                                {isExporting === "md" ? <Loader2 size={12} className="animate-spin" /> : <FileText size={12} />}
                                MD
                            </button>
                            <button
                                onClick={() => handleExport("pdf")}
                                disabled={isExporting !== "none"}
                                className={`flex-1 flex flex-shrink-0 items-center justify-center gap-1.5 px-2 py-1.5 disabled:opacity-50 text-white rounded-md text-[10px] font-medium transition-colors ${isExporting === "pdf" ? "bg-violet-600" : "hover:bg-white/10 border-x border-white/5"}`}
                            >
                                {isExporting === "pdf" ? <Loader2 size={12} className="animate-spin" /> : <FileDown size={12} />}
                                PDF
                            </button>
                            <button
                                onClick={() => handleExport("pptx")}
                                disabled={isExporting !== "none"}
                                className={`flex-1 flex flex-shrink-0 items-center justify-center gap-1.5 px-2 py-1.5 disabled:opacity-50 text-white rounded-md text-[10px] font-medium transition-colors ${isExporting === "pptx" ? "bg-violet-600" : "hover:bg-white/10"}`}
                            >
                                {isExporting === "pptx" ? <Loader2 size={12} className="animate-spin" /> : <File size={12} />}
                                PPTX
                            </button>
                        </div>
                    )}
                </div>
                <p className="text-white/40 text-xs mb-4 mt-2">
                    Findings continuously discovered by specialized AI agents.
                </p>

                {/* Filters */}
                <div className="flex gap-2">
                    {(["all", "summary", "contradiction", "research_gap"] as const).map(t => (
                        <button
                            key={t}
                            onClick={() => setFilter(t)}
                            className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors border ${filter === t
                                ? "bg-white/10 text-white border-white/20"
                                : "bg-transparent text-white/40 border-white/5 hover:text-white/70 hover:bg-white/5"
                                }`}
                        >
                            {t === "all" ? "All" : t.split("_").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")}
                        </button>
                    ))}
                </div>
            </div>

            <div className="flex-1 overflow-y-auto p-6 space-y-4">
                {isLoading && insights.length === 0 ? (
                    <div className="flex justify-center items-center py-10 text-white/40">
                        <Loader2 className="animate-spin" size={24} />
                    </div>
                ) : filteredInsights.length === 0 ? (
                    <div className="text-center py-10 text-white/40 text-sm">
                        No insights found for this filter.
                        <br />
                        Ask the agent to "summarize" or "find contradictions".
                    </div>
                ) : (
                    <AnimatePresence>
                        {filteredInsights.map(insight => {
                            const details = getTypeDetails(insight.type);
                            return (
                                <motion.div
                                    key={insight.id}
                                    initial={{ opacity: 0, scale: 0.95, y: 10 }}
                                    animate={{ opacity: 1, scale: 1, y: 0 }}
                                    className={`p-4 rounded-xl border ${details.border} bg-[#12121a] shadow-lg`}
                                >
                                    <div className="flex items-center justify-between mb-3">
                                        <div className={`flex items-center gap-2 text-xs font-semibold px-2 py-1 rounded-md ${details.bg} ${details.color}`}>
                                            {details.icon}
                                            {details.label}
                                        </div>
                                        <span className="text-[10px] text-white/30 flex items-center gap-1">
                                            <Clock size={10} />
                                            {new Date(insight.created_at).toLocaleDateString()}
                                        </span>
                                    </div>
                                    <div className="text-sm text-white/80 whitespace-pre-wrap leading-relaxed">
                                        {insight.content}
                                    </div>
                                </motion.div>
                            );
                        })}
                    </AnimatePresence>
                )}
            </div>
        </div>
    );
}

function SparklesIcon() {
    return (
        <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="text-purple-400"
        >
            <path d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
        </svg>
    );
}
